"""
Database module - JSON file utilities and data models.
"""

from .json_store import (
    DEFAULT_DATA_DIR,
    JSONParseError,
    JSONStoreError,
    WriteError,
    get_arxiv_categories,
    get_arxiv_categories_db,
    get_category_name,
    get_colleague_by_id,
    get_colleagues,
    get_colleagues_for_topics,
    get_delivery_policy,
    get_paper_by_id,
    get_papers_state,
    get_policy_for_importance,
    get_research_profile,
    get_research_topics,
    get_seen_paper_ids,
    get_stop_policy_from_profile,
    load_json,
    save_json,
    upsert_paper,
    upsert_papers,
    validate_categories,
)
from .models import (
    ArxivCategoriesDB,
    ArxivCategory,
    CalendarSettings,
    Colleague,
    ColleaguesDB,
    ColleagueSharingSettings,
    DeliveryPolicy,
    EmailSettings,
    GlobalSettings,
    ImportancePolicy,
    MyPaper,
    PaperRecord,
    PapersState,
    PapersStateStats,
    ReadingListSettings,
    ResearchProfile,
    StopPolicyConfig,
)

__all__ = [
    # JSON Store
    "load_json",
    "save_json",
    "DEFAULT_DATA_DIR",
    "JSONStoreError",
    "JSONParseError",
    "WriteError",
    # Research Profile
    "get_research_profile",
    "get_research_topics",
    "get_arxiv_categories",
    "get_stop_policy_from_profile",
    # Colleagues
    "get_colleagues",
    "get_colleague_by_id",
    "get_colleagues_for_topics",
    # Delivery Policy
    "get_delivery_policy",
    "get_policy_for_importance",
    # Papers State
    "get_papers_state",
    "get_seen_paper_ids",
    "get_paper_by_id",
    "upsert_paper",
    "upsert_papers",
    # arXiv Categories
    "get_arxiv_categories_db",
    "get_category_name",
    "validate_categories",
    # Models
    "ResearchProfile",
    "MyPaper",
    "StopPolicyConfig",
    "PaperRecord",
    "PapersState",
    "PapersStateStats",
    "Colleague",
    "ColleaguesDB",
    "DeliveryPolicy",
    "ImportancePolicy",
    "EmailSettings",
    "CalendarSettings",
    "ReadingListSettings",
    "ColleagueSharingSettings",
    "GlobalSettings",
    "ArxivCategory",
    "ArxivCategoriesDB",
]
